name: Branch Update
on:
  pull_request:
    paths-ignore:
      - .gitignore
      - README.md
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
